-- Esquema do banco, gerado das migrations (V001-V010). NÃO editar à mão.
-- Para regerar: scripts/gerar-schema.ps1 (precisa do Postgres local com a API em dev já ter subido).
-- Só o schema public, sem dono e sem permissões. O banco de produção é criado pelo Flyway a partir destas migrations.

--
--

\restrict rZAquwsHs6AMcQgOzVLREc496mz0mtxYhub1IzlK62LIf8d7U3EcxhWEvMVOOBu

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';

--
-- Name: adicional; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.adicional (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    produto_id uuid NOT NULL,
    recurso_id uuid NOT NULL,
    codigo character varying(60) NOT NULL,
    nome character varying(200) NOT NULL,
    quantidade numeric(12,2) NOT NULL,
    preco numeric(10,2) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    criado_em timestamp with time zone DEFAULT now() NOT NULL,
    sequencial bigint NOT NULL,
    CONSTRAINT adicional_preco_check CHECK ((preco >= (0)::numeric)),
    CONSTRAINT adicional_quantidade_check CHECK ((quantidade > (0)::numeric))
);

--
-- Name: adicional_sequencial_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.adicional ALTER COLUMN sequencial ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.adicional_sequencial_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: cliente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cliente (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tipo character varying(2) NOT NULL,
    documento character varying(20) NOT NULL,
    nome character varying(200) NOT NULL,
    logradouro character varying(200),
    numero character varying(20),
    complemento character varying(100),
    bairro character varying(100),
    cidade character varying(100),
    uf character varying(2),
    cep character varying(9),
    criado_em timestamp with time zone DEFAULT now() NOT NULL,
    sequencial bigint NOT NULL,
    CONSTRAINT cliente_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['PF'::character varying, 'PJ'::character varying])::text[])))
);

--
-- Name: cliente_contato; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cliente_contato (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    cliente_id uuid NOT NULL,
    nome character varying(200) NOT NULL,
    email character varying(200),
    telefone character varying(30),
    principal boolean DEFAULT false NOT NULL
);

--
-- Name: cliente_sequencial_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cliente ALTER COLUMN sequencial ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cliente_sequencial_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: cobranca; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cobranca (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    contratacao_id uuid NOT NULL,
    competencia_inicio date NOT NULL,
    competencia_fim date NOT NULL,
    vencimento date NOT NULL,
    valor numeric(10,2) NOT NULL,
    status character varying(20) DEFAULT 'ABERTA'::character varying NOT NULL,
    pago_em date,
    valor_pago numeric(10,2),
    forma_pagamento character varying(20),
    observacao text,
    registrado_por uuid,
    criado_em timestamp with time zone DEFAULT now() NOT NULL,
    sequencial bigint NOT NULL,
    CONSTRAINT cobranca_check CHECK ((competencia_fim >= competencia_inicio)),
    CONSTRAINT cobranca_check1 CHECK ((((status)::text <> 'PAGA'::text) OR ((pago_em IS NOT NULL) AND (valor_pago IS NOT NULL) AND (forma_pagamento IS NOT NULL)))),
    CONSTRAINT cobranca_status_check CHECK (((status)::text = ANY ((ARRAY['ABERTA'::character varying, 'PAGA'::character varying, 'CANCELADA'::character varying, 'ISENTA'::character varying])::text[]))),
    CONSTRAINT cobranca_valor_check CHECK ((valor >= (0)::numeric)),
    CONSTRAINT cobranca_valor_pago_check CHECK (((valor_pago IS NULL) OR (valor_pago >= (0)::numeric)))
);

--
-- Name: cobranca_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cobranca_item (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    cobranca_id uuid NOT NULL,
    ordem integer NOT NULL,
    tipo character varying(20) NOT NULL,
    descricao character varying(300) NOT NULL,
    quantidade numeric(12,2) NOT NULL,
    valor_unitario numeric(10,2) NOT NULL,
    meses integer NOT NULL,
    valor numeric(10,2) NOT NULL,
    CONSTRAINT cobranca_item_meses_check CHECK ((meses > 0)),
    CONSTRAINT cobranca_item_quantidade_check CHECK ((quantidade > (0)::numeric)),
    CONSTRAINT cobranca_item_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['PLANO'::character varying, 'ADICIONAL'::character varying])::text[]))),
    CONSTRAINT cobranca_item_valor_check CHECK ((valor >= (0)::numeric)),
    CONSTRAINT cobranca_item_valor_unitario_check CHECK ((valor_unitario >= (0)::numeric))
);

--
-- Name: COLUMN cobranca_item.valor_unitario; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.cobranca_item.valor_unitario IS 'PLANO: preço do período. ADICIONAL: preço mensal do pacote; valor = quantidade × unitário × meses.';

--
-- Name: cobranca_sequencial_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cobranca ALTER COLUMN sequencial ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cobranca_sequencial_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: contratacao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contratacao (
    id uuid NOT NULL,
    cliente_id uuid NOT NULL,
    produto_id uuid NOT NULL,
    plano_id uuid NOT NULL,
    periodicidade character varying(10) NOT NULL,
    valor numeric(10,2) NOT NULL,
    dia_vencimento integer NOT NULL,
    inicio date NOT NULL,
    vigente_ate date,
    situacao_comercial character varying(20) NOT NULL,
    situacao_provisionamento character varying(20) DEFAULT 'PENDENTE'::character varying NOT NULL,
    idempotency_key uuid NOT NULL,
    id_externo uuid,
    nome_instancia character varying(200) NOT NULL,
    slug_instancia character varying(80) NOT NULL,
    admin_nome character varying(200) NOT NULL,
    admin_email character varying(200) NOT NULL,
    motivo_bloqueio text,
    versao_direitos integer NOT NULL,
    direitos_atuais jsonb NOT NULL,
    observacoes text,
    criado_em timestamp with time zone DEFAULT now() NOT NULL,
    ultimo_status_provisionamento integer,
    sequencial bigint NOT NULL,
    isenta boolean DEFAULT false NOT NULL,
    isencao_motivo text,
    isenta_ate date,
    CONSTRAINT contratacao_dia_vencimento_check CHECK (((dia_vencimento >= 1) AND (dia_vencimento <= 28))),
    CONSTRAINT contratacao_isencao_check CHECK (((NOT isenta) OR (isencao_motivo IS NOT NULL))),
    CONSTRAINT contratacao_periodicidade_check CHECK (((periodicidade)::text = ANY ((ARRAY['MENSAL'::character varying, 'TRIMESTRAL'::character varying, 'SEMESTRAL'::character varying, 'ANUAL'::character varying])::text[]))),
    CONSTRAINT contratacao_situacao_comercial_check CHECK (((situacao_comercial)::text = ANY ((ARRAY['TRIAL'::character varying, 'ATIVA'::character varying, 'INADIMPLENTE'::character varying, 'BLOQUEADA'::character varying, 'CANCELADA'::character varying])::text[]))),
    CONSTRAINT contratacao_situacao_provisionamento_check CHECK (((situacao_provisionamento)::text = ANY ((ARRAY['PENDENTE'::character varying, 'PROCESSANDO'::character varying, 'ATIVA'::character varying, 'ERRO'::character varying])::text[]))),
    CONSTRAINT contratacao_valor_check CHECK ((valor >= (0)::numeric)),
    CONSTRAINT contratacao_versao_direitos_check CHECK ((versao_direitos > 0))
);

--
-- Name: COLUMN contratacao.idempotency_key; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.contratacao.idempotency_key IS 'Sempre igual ao id: o app exige Idempotency-Key = contratacaoId do corpo.';

--
-- Name: COLUMN contratacao.ultimo_status_provisionamento; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.contratacao.ultimo_status_provisionamento IS 'Status HTTP da última resposta ao provisionamento; 0 = sem resposta; NULL = nunca enviado.';

--
-- Name: COLUMN contratacao.isenta_ate; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.contratacao.isenta_ate IS 'Último dia da última competência isenta. Vazio com isenta = sem data para acabar.';

--
-- Name: contratacao_adicional; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contratacao_adicional (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    contratacao_id uuid NOT NULL,
    adicional_id uuid NOT NULL,
    quantidade numeric(12,2) NOT NULL,
    CONSTRAINT contratacao_adicional_quantidade_check CHECK ((quantidade > (0)::numeric))
);

--
-- Name: contratacao_sequencial_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contratacao ALTER COLUMN sequencial ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contratacao_sequencial_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: erro_aplicativo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.erro_aplicativo (
    id uuid NOT NULL,
    produto_id uuid NOT NULL,
    contratacao_id uuid,
    tenant_id uuid,
    usuario_id uuid,
    ocorrido_em timestamp with time zone NOT NULL,
    recebido_em timestamp with time zone DEFAULT now() NOT NULL,
    metodo character varying(10),
    rota character varying(300),
    status integer NOT NULL,
    codigo character varying(60),
    mensagem character varying(1000),
    request_id character varying(100)
);

--
-- Name: evento_saida; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evento_saida (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    contratacao_id uuid NOT NULL,
    produto_codigo character varying(40) NOT NULL,
    tipo character varying(40) NOT NULL,
    versao integer NOT NULL,
    payload jsonb NOT NULL,
    situacao character varying(20) DEFAULT 'PENDENTE'::character varying NOT NULL,
    tentativas integer DEFAULT 0 NOT NULL,
    proxima_tentativa timestamp with time zone DEFAULT now() NOT NULL,
    criado_em timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT evento_saida_situacao_check CHECK (((situacao)::text = ANY ((ARRAY['PENDENTE'::character varying, 'ENVIADO'::character varying, 'DESCARTADO'::character varying, 'FALHOU'::character varying])::text[])))
);

--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);

--
-- Name: historico_contratacao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.historico_contratacao (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    contratacao_id uuid NOT NULL,
    operador_id uuid,
    acao character varying(40) NOT NULL,
    motivo text,
    versao_direitos integer NOT NULL,
    criado_em timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: integracao_nonce; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.integracao_nonce (
    chave_id character varying(80) NOT NULL,
    nonce character varying(80) NOT NULL,
    recebido_em timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: operador; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.operador (
    id uuid NOT NULL,
    nome character varying(160) NOT NULL,
    email character varying(180) NOT NULL,
    senha_hash character varying(120) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    criado_em timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: operador_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.operador_log (
    id uuid NOT NULL,
    operador_id uuid,
    acao character varying(40) NOT NULL,
    detalhe character varying(500),
    ip character varying(64),
    criado_em timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: plano; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plano (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    produto_id uuid NOT NULL,
    codigo character varying(60) NOT NULL,
    nome character varying(200) NOT NULL,
    ativo boolean DEFAULT true NOT NULL,
    criado_em timestamp with time zone DEFAULT now() NOT NULL,
    sequencial bigint NOT NULL
);

--
-- Name: plano_recurso; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plano_recurso (
    plano_id uuid NOT NULL,
    recurso_id uuid NOT NULL,
    valor numeric(12,2) NOT NULL,
    CONSTRAINT plano_recurso_valor_check CHECK ((valor >= (0)::numeric))
);

--
-- Name: plano_sequencial_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plano ALTER COLUMN sequencial ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plano_sequencial_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: preco_plano; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.preco_plano (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    plano_id uuid NOT NULL,
    periodicidade character varying(10) NOT NULL,
    valor numeric(10,2) NOT NULL,
    vigente_desde date NOT NULL,
    criado_em timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT preco_plano_periodicidade_check CHECK (((periodicidade)::text = ANY ((ARRAY['MENSAL'::character varying, 'TRIMESTRAL'::character varying, 'SEMESTRAL'::character varying, 'ANUAL'::character varying])::text[]))),
    CONSTRAINT preco_plano_valor_check CHECK ((valor >= (0)::numeric))
);

--
-- Name: produto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.produto (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    codigo character varying(40) NOT NULL,
    nome character varying(200) NOT NULL,
    url_base_integracao character varying(300),
    ativo boolean DEFAULT true NOT NULL,
    criado_em timestamp with time zone DEFAULT now() NOT NULL,
    sequencial bigint NOT NULL
);

--
-- Name: produto_sequencial_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.produto ALTER COLUMN sequencial ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produto_sequencial_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: recurso; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recurso (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    produto_id uuid NOT NULL,
    codigo character varying(60) NOT NULL,
    nome character varying(200) NOT NULL,
    tipo character varying(20) NOT NULL,
    unidade character varying(40),
    valor_padrao numeric(12,2),
    sequencial bigint NOT NULL,
    CONSTRAINT recurso_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['LIMITE'::character varying, 'FUNCIONALIDADE'::character varying])::text[]))),
    CONSTRAINT recurso_valor_padrao_check CHECK (((valor_padrao IS NULL) OR (valor_padrao >= (0)::numeric)))
);

--
-- Name: recurso_sequencial_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recurso ALTER COLUMN sequencial ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recurso_sequencial_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_token (
    id uuid NOT NULL,
    operador_id uuid NOT NULL,
    token_hash character varying(64) NOT NULL,
    expira_em timestamp with time zone NOT NULL,
    revogado_em timestamp with time zone,
    substituido_por uuid,
    ip character varying(64),
    criado_em timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: adicional adicional_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.adicional
    ADD CONSTRAINT adicional_pkey PRIMARY KEY (id);

--
-- Name: adicional adicional_produto_id_codigo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.adicional
    ADD CONSTRAINT adicional_produto_id_codigo_key UNIQUE (produto_id, codigo);

--
-- Name: adicional adicional_sequencial_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.adicional
    ADD CONSTRAINT adicional_sequencial_key UNIQUE (sequencial);

--
-- Name: cliente_contato cliente_contato_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente_contato
    ADD CONSTRAINT cliente_contato_pkey PRIMARY KEY (id);

--
-- Name: cliente cliente_documento_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_documento_key UNIQUE (documento);

--
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (id);

--
-- Name: cliente cliente_sequencial_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_sequencial_key UNIQUE (sequencial);

--
-- Name: cobranca_item cobranca_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cobranca_item
    ADD CONSTRAINT cobranca_item_pkey PRIMARY KEY (id);

--
-- Name: cobranca cobranca_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cobranca
    ADD CONSTRAINT cobranca_pkey PRIMARY KEY (id);

--
-- Name: cobranca cobranca_sequencial_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cobranca
    ADD CONSTRAINT cobranca_sequencial_key UNIQUE (sequencial);

--
-- Name: contratacao_adicional contratacao_adicional_contratacao_id_adicional_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contratacao_adicional
    ADD CONSTRAINT contratacao_adicional_contratacao_id_adicional_id_key UNIQUE (contratacao_id, adicional_id);

--
-- Name: contratacao_adicional contratacao_adicional_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contratacao_adicional
    ADD CONSTRAINT contratacao_adicional_pkey PRIMARY KEY (id);

--
-- Name: contratacao contratacao_idempotency_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contratacao
    ADD CONSTRAINT contratacao_idempotency_key_key UNIQUE (idempotency_key);

--
-- Name: contratacao contratacao_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contratacao
    ADD CONSTRAINT contratacao_pkey PRIMARY KEY (id);

--
-- Name: contratacao contratacao_sequencial_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contratacao
    ADD CONSTRAINT contratacao_sequencial_key UNIQUE (sequencial);

--
-- Name: erro_aplicativo erro_aplicativo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.erro_aplicativo
    ADD CONSTRAINT erro_aplicativo_pkey PRIMARY KEY (id);

--
-- Name: evento_saida evento_saida_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evento_saida
    ADD CONSTRAINT evento_saida_pkey PRIMARY KEY (id);

--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);

--
-- Name: historico_contratacao historico_contratacao_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historico_contratacao
    ADD CONSTRAINT historico_contratacao_pkey PRIMARY KEY (id);

--
-- Name: integracao_nonce integracao_nonce_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.integracao_nonce
    ADD CONSTRAINT integracao_nonce_pkey PRIMARY KEY (chave_id, nonce);

--
-- Name: operador_log operador_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operador_log
    ADD CONSTRAINT operador_log_pkey PRIMARY KEY (id);

--
-- Name: operador operador_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operador
    ADD CONSTRAINT operador_pkey PRIMARY KEY (id);

--
-- Name: plano plano_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plano
    ADD CONSTRAINT plano_pkey PRIMARY KEY (id);

--
-- Name: plano plano_produto_id_codigo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plano
    ADD CONSTRAINT plano_produto_id_codigo_key UNIQUE (produto_id, codigo);

--
-- Name: plano_recurso plano_recurso_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plano_recurso
    ADD CONSTRAINT plano_recurso_pkey PRIMARY KEY (plano_id, recurso_id);

--
-- Name: plano plano_sequencial_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plano
    ADD CONSTRAINT plano_sequencial_key UNIQUE (sequencial);

--
-- Name: preco_plano preco_plano_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.preco_plano
    ADD CONSTRAINT preco_plano_pkey PRIMARY KEY (id);

--
-- Name: preco_plano preco_plano_plano_id_periodicidade_vigente_desde_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.preco_plano
    ADD CONSTRAINT preco_plano_plano_id_periodicidade_vigente_desde_key UNIQUE (plano_id, periodicidade, vigente_desde);

--
-- Name: produto produto_codigo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produto
    ADD CONSTRAINT produto_codigo_key UNIQUE (codigo);

--
-- Name: produto produto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produto
    ADD CONSTRAINT produto_pkey PRIMARY KEY (id);

--
-- Name: produto produto_sequencial_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produto
    ADD CONSTRAINT produto_sequencial_key UNIQUE (sequencial);

--
-- Name: recurso recurso_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recurso
    ADD CONSTRAINT recurso_pkey PRIMARY KEY (id);

--
-- Name: recurso recurso_produto_id_codigo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recurso
    ADD CONSTRAINT recurso_produto_id_codigo_key UNIQUE (produto_id, codigo);

--
-- Name: recurso recurso_sequencial_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recurso
    ADD CONSTRAINT recurso_sequencial_key UNIQUE (sequencial);

--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);

--
-- Name: operador uk_operador_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operador
    ADD CONSTRAINT uk_operador_email UNIQUE (email);

--
-- Name: refresh_token uk_refresh_token_hash; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash);

--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);

--
-- Name: idx_cobranca_contratacao_status_vencimento; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cobranca_contratacao_status_vencimento ON public.cobranca USING btree (contratacao_id, status, vencimento);

--
-- Name: idx_cobranca_item_cobranca; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cobranca_item_cobranca ON public.cobranca_item USING btree (cobranca_id, ordem);

--
-- Name: idx_erro_aplicativo_contratacao; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_erro_aplicativo_contratacao ON public.erro_aplicativo USING btree (contratacao_id, ocorrido_em DESC);

--
-- Name: idx_erro_aplicativo_ocorrido; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_erro_aplicativo_ocorrido ON public.erro_aplicativo USING btree (ocorrido_em DESC);

--
-- Name: idx_evento_saida_pendente; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_evento_saida_pendente ON public.evento_saida USING btree (situacao, proxima_tentativa);

--
-- Name: idx_historico_contratacao; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_historico_contratacao ON public.historico_contratacao USING btree (contratacao_id, criado_em);

--
-- Name: uq_cobranca_competencia_vigente; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_cobranca_competencia_vigente ON public.cobranca USING btree (contratacao_id, competencia_inicio) WHERE ((status)::text <> 'CANCELADA'::text);

--
-- Name: uq_contratacao_externo; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_contratacao_externo ON public.contratacao USING btree (produto_id, id_externo) WHERE (id_externo IS NOT NULL);

--
-- Name: uq_contratacao_slug; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_contratacao_slug ON public.contratacao USING btree (produto_id, slug_instancia);

--
-- Name: adicional adicional_produto_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.adicional
    ADD CONSTRAINT adicional_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.produto(id);

--
-- Name: adicional adicional_recurso_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.adicional
    ADD CONSTRAINT adicional_recurso_id_fkey FOREIGN KEY (recurso_id) REFERENCES public.recurso(id);

--
-- Name: cliente_contato cliente_contato_cliente_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente_contato
    ADD CONSTRAINT cliente_contato_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.cliente(id);

--
-- Name: cobranca cobranca_contratacao_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cobranca
    ADD CONSTRAINT cobranca_contratacao_id_fkey FOREIGN KEY (contratacao_id) REFERENCES public.contratacao(id);

--
-- Name: cobranca_item cobranca_item_cobranca_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cobranca_item
    ADD CONSTRAINT cobranca_item_cobranca_id_fkey FOREIGN KEY (cobranca_id) REFERENCES public.cobranca(id) ON DELETE CASCADE;

--
-- Name: cobranca cobranca_registrado_por_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cobranca
    ADD CONSTRAINT cobranca_registrado_por_fkey FOREIGN KEY (registrado_por) REFERENCES public.operador(id);

--
-- Name: contratacao_adicional contratacao_adicional_adicional_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contratacao_adicional
    ADD CONSTRAINT contratacao_adicional_adicional_id_fkey FOREIGN KEY (adicional_id) REFERENCES public.adicional(id);

--
-- Name: contratacao_adicional contratacao_adicional_contratacao_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contratacao_adicional
    ADD CONSTRAINT contratacao_adicional_contratacao_id_fkey FOREIGN KEY (contratacao_id) REFERENCES public.contratacao(id);

--
-- Name: contratacao contratacao_cliente_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contratacao
    ADD CONSTRAINT contratacao_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.cliente(id);

--
-- Name: contratacao contratacao_plano_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contratacao
    ADD CONSTRAINT contratacao_plano_id_fkey FOREIGN KEY (plano_id) REFERENCES public.plano(id);

--
-- Name: contratacao contratacao_produto_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contratacao
    ADD CONSTRAINT contratacao_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.produto(id);

--
-- Name: erro_aplicativo erro_aplicativo_contratacao_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.erro_aplicativo
    ADD CONSTRAINT erro_aplicativo_contratacao_id_fkey FOREIGN KEY (contratacao_id) REFERENCES public.contratacao(id);

--
-- Name: erro_aplicativo erro_aplicativo_produto_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.erro_aplicativo
    ADD CONSTRAINT erro_aplicativo_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.produto(id);

--
-- Name: evento_saida evento_saida_contratacao_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evento_saida
    ADD CONSTRAINT evento_saida_contratacao_id_fkey FOREIGN KEY (contratacao_id) REFERENCES public.contratacao(id);

--
-- Name: operador_log fk_operador_log_operador; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operador_log
    ADD CONSTRAINT fk_operador_log_operador FOREIGN KEY (operador_id) REFERENCES public.operador(id);

--
-- Name: refresh_token fk_refresh_token_operador; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT fk_refresh_token_operador FOREIGN KEY (operador_id) REFERENCES public.operador(id);

--
-- Name: historico_contratacao historico_contratacao_contratacao_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historico_contratacao
    ADD CONSTRAINT historico_contratacao_contratacao_id_fkey FOREIGN KEY (contratacao_id) REFERENCES public.contratacao(id);

--
-- Name: historico_contratacao historico_contratacao_operador_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historico_contratacao
    ADD CONSTRAINT historico_contratacao_operador_id_fkey FOREIGN KEY (operador_id) REFERENCES public.operador(id);

--
-- Name: plano plano_produto_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plano
    ADD CONSTRAINT plano_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.produto(id);

--
-- Name: plano_recurso plano_recurso_plano_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plano_recurso
    ADD CONSTRAINT plano_recurso_plano_id_fkey FOREIGN KEY (plano_id) REFERENCES public.plano(id);

--
-- Name: plano_recurso plano_recurso_recurso_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plano_recurso
    ADD CONSTRAINT plano_recurso_recurso_id_fkey FOREIGN KEY (recurso_id) REFERENCES public.recurso(id);

--
-- Name: preco_plano preco_plano_plano_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.preco_plano
    ADD CONSTRAINT preco_plano_plano_id_fkey FOREIGN KEY (plano_id) REFERENCES public.plano(id);

--
-- Name: recurso recurso_produto_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recurso
    ADD CONSTRAINT recurso_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.produto(id);

--
-- Name: adicional; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.adicional ENABLE ROW LEVEL SECURITY;

--
-- Name: cliente; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.cliente ENABLE ROW LEVEL SECURITY;

--
-- Name: cliente_contato; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.cliente_contato ENABLE ROW LEVEL SECURITY;

--
-- Name: cobranca; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.cobranca ENABLE ROW LEVEL SECURITY;

--
-- Name: cobranca_item; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.cobranca_item ENABLE ROW LEVEL SECURITY;

--
-- Name: contratacao; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.contratacao ENABLE ROW LEVEL SECURITY;

--
-- Name: contratacao_adicional; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.contratacao_adicional ENABLE ROW LEVEL SECURITY;

--
-- Name: erro_aplicativo; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.erro_aplicativo ENABLE ROW LEVEL SECURITY;

--
-- Name: evento_saida; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.evento_saida ENABLE ROW LEVEL SECURITY;

--
-- Name: historico_contratacao; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.historico_contratacao ENABLE ROW LEVEL SECURITY;

--
-- Name: integracao_nonce; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.integracao_nonce ENABLE ROW LEVEL SECURITY;

--
-- Name: operador; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.operador ENABLE ROW LEVEL SECURITY;

--
-- Name: operador_log; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.operador_log ENABLE ROW LEVEL SECURITY;

--
-- Name: plano; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.plano ENABLE ROW LEVEL SECURITY;

--
-- Name: plano_recurso; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.plano_recurso ENABLE ROW LEVEL SECURITY;

--
-- Name: preco_plano; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.preco_plano ENABLE ROW LEVEL SECURITY;

--
-- Name: produto; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.produto ENABLE ROW LEVEL SECURITY;

--
-- Name: recurso; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.recurso ENABLE ROW LEVEL SECURITY;

--
-- Name: refresh_token; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.refresh_token ENABLE ROW LEVEL SECURITY;

--
--

\unrestrict rZAquwsHs6AMcQgOzVLREc496mz0mtxYhub1IzlK62LIf8d7U3EcxhWEvMVOOBu

