-- Número curto e sequencial para o operador ditar e copiar (teste de telas de
-- 26/09/2026): o id continua sendo o uuid; o número é só para gente. Coluna
-- identity preenche também as linhas que já existem.

ALTER TABLE public.cliente     ADD COLUMN sequencial bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE public.contratacao ADD COLUMN sequencial bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE public.cobranca    ADD COLUMN sequencial bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE public.produto     ADD COLUMN sequencial bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE public.plano       ADD COLUMN sequencial bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE public.adicional   ADD COLUMN sequencial bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
ALTER TABLE public.recurso     ADD COLUMN sequencial bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;
